/**
 * This file is generated by vite-plugin-sveltekit-api-codegen.
 * Do not edit this file directly, it will be overwritten.
 */

export default {
    api: {
        /**
         * POST /api
         */
        async POST(init?: RequestInit): Promise<any> {
            return fetch(`/api`, {
                method: 'POST',
                ...init,
            }).then((res) => res.json());
        },
    },

    auth: {
        oauth: {
            github: {
                /**
                 * GET /auth/oauth/github
                 */
                async GET(init?: RequestInit): Promise<any> {
                    return fetch(`/auth/oauth/github`, {
                        method: 'GET',
                        ...init,
                    }).then((res) => res.json());
                },

                callback: {
                    /**
                     * GET /auth/oauth/github/callback
                     */
                    async GET(init?: RequestInit): Promise<any> {
                        return fetch(`/auth/oauth/github/callback`, {
                            method: 'GET',
                            ...init,
                        }).then((res) => res.json());
                    },
                },
            },

            google: {
                /**
                 * GET /auth/oauth/google
                 */
                async GET(init?: RequestInit): Promise<any> {
                    return fetch(`/auth/oauth/google`, {
                        method: 'GET',
                        ...init,
                    }).then((res) => res.json());
                },

                callback: {
                    /**
                     * GET /auth/oauth/google/callback
                     */
                    async GET(init?: RequestInit): Promise<any> {
                        return fetch(`/auth/oauth/google/callback`, {
                            method: 'GET',
                            ...init,
                        }).then((res) => res.json());
                    },
                },
            },
        },
    },
};
