/**
 * This file is generated by vite-plugin-sveltekit-api-codegen.
 * Do not edit this file directly, it will be overwritten.
 */

export default {
    api: {
        projects: {
            /**
             * POST /api/projects
             */
            async POST(
                init?: RequestInit,
            ): Promise<{ id: FormDataEntryValue | null }> {
                return fetch(`/api/projects`, {
                    method: 'POST',
                    ...init,
                }).then((res) => res.json());
            },

            /**
             * GET /api/projects
             */
            async GET(init?: RequestInit): Promise<any> {
                return fetch(`/api/projects`, {
                    method: 'GET',
                    ...init,
                }).then((res) => res.json());
            },
        },
    },

    auth: {
        oauth: {
            github: {
                /**
                 * GET /auth/oauth/github
                 */
                async GET(init?: RequestInit): Promise<any> {
                    return fetch(`/auth/oauth/github`, {
                        method: 'GET',
                        ...init,
                    }).then((res) => res.json());
                },

                callback: {
                    /**
                     * GET /auth/oauth/github/callback
                     */
                    async GET(init?: RequestInit): Promise<any> {
                        return fetch(`/auth/oauth/github/callback`, {
                            method: 'GET',
                            ...init,
                        }).then((res) => res.json());
                    },
                },
            },

            google: {
                /**
                 * GET /auth/oauth/google
                 */
                async GET(init?: RequestInit): Promise<any> {
                    return fetch(`/auth/oauth/google`, {
                        method: 'GET',
                        ...init,
                    }).then((res) => res.json());
                },

                callback: {
                    /**
                     * GET /auth/oauth/google/callback
                     */
                    async GET(init?: RequestInit): Promise<any> {
                        return fetch(`/auth/oauth/google/callback`, {
                            method: 'GET',
                            ...init,
                        }).then((res) => res.json());
                    },
                },
            },
        },
    },
};
